Context wired up for Leaderboard and Alerts with CSS fixes
Lambda-School-Labs/bg-emotion-tracker-fe pull request #109
Opened 2021-06-18 15:47 UTC by ashtilawat23

Description
Wired up context for Alerts and Leaderboard. Data is coming in for both pages. Fixed CSS problems on Leaderboard.

What did you change?
Context added to both pages.

2021-06-18 15:53 UTC, fidan93 approved these changes
looks good 👍

2021-06-18 16:23 UTC, L-Steinmacher requested changes
Add .length to line 19 in RenderAlerts.js as well as move the key from line 37 to line 36 in the same file.

2021-06-18 16:23 UTC, L-Steinmacher commented on src/components/pages/Leaderboard/RenderLeaderboard.js
> +import { ConsoleWriter } from 'istanbul-lib-report';
What is this?

2021-06-18 16:23 UTC, L-Steinmacher commented on src/components/pages/Alerts/RenderAlerts.js
> +    if (context.memberReactions === 0) {
add .length

2021-06-18 16:23 UTC, L-Steinmacher commented on src/components/pages/Alerts/RenderAlerts.js
> +              <div label={club.clubname}>
Key may have to be on top level div in a map.

2021-06-18 19:11 UTC, ashtilawat23 commented on src/components/pages/Leaderboard/RenderLeaderboard.js
> +import { ConsoleWriter } from 'istanbul-lib-report';
I removed it,

2021-06-21 15:59 UTC, L-Steinmacher approved these changes
Looks good and well organized.

2021-06-21 16:22 UTC, merged